# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compare two sets of TLSH hashes, return the count of how many
#' similar hashes there are.
#'
#' @param xs list of TLSH hashes
#' @param xs2 list of TLSH hashes
#' @return integer showing the union count between the two sets.
#' @description calculates the union of two TLSH lists given some
#'   threshold.
#' @usage
#' out <- tlsh_n_union(tlsh_set_a, tlsh_set_b)
tlsh_n_union <- function(threshold, xs, xs2) {
    .Call(`_tlshtree_tlsh_n_union`, threshold, xs, xs2)
}

#' Calculate the distance between two TLSH hashes
#'
#' @param a TLSH hash string
#' @param b TLSH hash string
#' @return integer representing the distance between the two hashes
#' @description negative values indicate one of the two hashes is invalid
#' @usage
#' out <- tlsh_diff(tlsh_a, tlsh_b)
tlsh_diff <- function(a, b) {
    .Call(`_tlshtree_tlsh_diff`, a, b)
}

#' Returns simple information about the tree
#'
#' @param tlshtree value from creating with tlsh_tree_new
#' @return List object with information about the tree
#' @usage
#' out <- tlsh_tree_info(tree)
tlsh_tree_info <- function(tree) {
    .Call(`_tlshtree_tlsh_tree_info`, tree)
}

#' Creates a new TLSH tree given the vector of TLSH hashes
#'
#' @param leaf_size is the set size of each leaf, minimum size is 20
#' @param xs is a vector of TLSH hashes
#' @return tlshtree pointer
#' @usage
#' out <- tlsh_tree_new(hashes, 20)
tlsh_tree_new <- function(leaf_size, xs) {
    .Call(`_tlshtree_tlsh_tree_new`, leaf_size, xs)
}

#' For each TLSH hash, find all matches it has within the tree, given
#' some threshold
#'
#' @param tlshtree value from creating with tlsh_tree_new
#' @param threshold is the maximum distance to be considered a pair
#' @param xs is a vector of TLSH hashes
#' @return a list with all the TLSH hash matches for each key in
#' the input vector
#' @usage
#' out <- tlsh_tree_matches(10, hashes)
tlsh_tree_matches <- function(tree, threshold, keys) {
    .Call(`_tlshtree_tlsh_tree_matches`, tree, threshold, keys)
}

#' For each TLSH hash, count how many matches it has within the tree, given
#' some threshold
#'
#' @param tlshtree value from creating with tlsh_tree_new
#' @param threshold is the maximum distance to be considered a pair
#' @param xs is a vector of TLSH hashes
#' @return a count of how many pairs are in the vector
#' @usage
#' out <- tlsh_tree_n_matches(10, hashes)
tlsh_tree_n_matches <- function(tree, threshold, keys) {
    .Call(`_tlshtree_tlsh_tree_n_matches`, tree, threshold, keys)
}

#' Given a vector of tlsh hashes, return a count of all the pairwise matches
#' given some threshold
#'
#' @param threshold is the maximum distance to be considered a pair
#' @param xs is a vector of TLSH hashes
#' @return a count of how many pairs are in the vector
#' @usage
#' out <- tlsh_n_pairs(10, hashes)
tlsh_n_pairs <- function(threshold, xs) {
    .Call(`_tlshtree_tlsh_n_pairs`, threshold, xs)
}

#' Deletes a TLSH hash from an existing tree.
#'
#' @param tlshtree value from creating with tlsh_tree_new
#' @param key_str is the TLSH hash to be deleted
#' @return a pointer to the tlshtree
#' @usage
#' tree <- tlsh_tree_delete(tree, tlsh_hash)
tlsh_tree_delete <- function(tree, key_str) {
    .Call(`_tlshtree_tlsh_tree_delete`, tree, key_str)
}

#' Adds a TLSH hash to an existing tree.
#'
#' @param tlshtree value from creating with tlsh_tree_new
#' @param key_str is the TLSH hash to be added
#' @return a pointer to the tlshtree
#' @description Adds a TLSH hash to an existing tree. This will not
#' rebuild the structure of the existing tree, only the hash will be added to
#' the appropriate leaf. The
#' underlying point value of the tree will not change, but this function
#' returns that pointer value regardless, so the return value can be
#' ignored for most use cases.
#' @usage
#' tree <- tlsh_tree_add(tree, tlsh_hash)
tlsh_tree_add <- function(tree, key_str) {
    .Call(`_tlshtree_tlsh_tree_add`, tree, key_str)
}

#' Transform a string into a vector of TLSH hashes
#'
#' @param s a string
#' @return a TLSH hash
#' @usage
#' out <- tlsh_from_str(string_val_gt_50)
tlsh_from_str <- function(s) {
    .Call(`_tlshtree_tlsh_from_str`, s)
}

#' Transform a vector of strings into a vector of TLSH hashes
#'
#' @param xs vector of strings
#' @return vector of TLSH hashes
#' @usage
#' df <- read.csv('test.csv')
#' names(df) <- c('raw_string_value')
#' df <- df %>%
#'   mutate(tlsh_hash = tlsh_from_strs(raw_string_value))
tlsh_from_strs <- function(xs) {
    .Call(`_tlshtree_tlsh_from_strs`, xs)
}

